# Generated by Django 5.0.6 on 2024-07-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactform_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
